on:
    push:
      branches:
        - main
    workflow_dispatch:
  
env:
    # change to your application's name in Azure
    AZURE_WEBAPP_NAME: customerdemo-react
    # change both instances of azure-react-apod to the name of your repo
    AZURE_WEBAPP_PACKAGE_PATH: '/home/runner/work/azure-react-apod/azure-react-apod'   
    # set this to the node version to use if not 16
    NODE_VERSION: '16.x'                
    # NASA API key recorded as GitHub secret, delete if you haven't followed APOD section
    REACT_APP_NASA_API_KEY: ${{ secrets.REACT_APP_NASA_API_KEY }}   
    
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
  
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present                
  
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./build
  
    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
  
  
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp 
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}